namespace LinkNest.Shared.Resources;

/// <summary>
/// In-memory English and Arabic UI string catalog used by Blazor WebAssembly when
/// <see cref="Microsoft.Extensions.Localization.IStringLocalizer"/> resources are unavailable.
/// </summary>
/// <remarks>
/// Keys mirror entries in <c>SharedResource.resx</c>. English is the fallback when a key
/// or culture is missing.
/// </remarks>
public static class LocalizationCatalog
{
    private static readonly Dictionary<string, Dictionary<string, string>> Strings = new(StringComparer.OrdinalIgnoreCase)
    {
        ["en"] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["AppTitle"] = "LinkNest",
            ["Home"] = "Home",
            ["Archive"] = "Archive",
            ["FavoriteCategories"] = "Favorite Categories",
            ["AllCategories"] = "All Categories",
            ["AddCategory"] = "Add Category",
            ["CategoryName"] = "Category name",
            ["Create"] = "Create",
            ["Delete"] = "Delete",
            ["Restore"] = "Restore",
            ["Favorite"] = "Favorite",
            ["Unfavorite"] = "Unfavorite",
            ["Open"] = "Open",
            ["Back"] = "Back",
            ["FavoriteLinks"] = "Favorite Links",
            ["AllLinks"] = "All Links",
            ["AddLink"] = "Add Link",
            ["LinkTitleEn"] = "Title (English, optional)",
            ["LinkTitleAr"] = "Title (Arabic, optional)",
            ["SearchLinks"] = "Search links by title or URL",
            ["NoSearchResults"] = "No links match your search.",
            ["LinkTitle"] = "Title (optional)",
            ["LinkUrl"] = "URL",
            ["LinkNote"] = "Note (optional)",
            ["LoadingPreview"] = "Loading preview...",
            ["PreviewUnavailable"] = "Preview unavailable",
            ["ArchivedItems"] = "Archived Items",
            ["ArchivedCategories"] = "Archived Categories",
            ["ArchivedLinks"] = "Archived Links",
            ["ArchiveRetentionNotice"] = "Items stay in archive for 7 days before permanent deletion.",
            ["NoCategoriesYet"] = "No categories yet. Create your first meal category.",
            ["NoLinksYet"] = "No links yet. Add your first link.",
            ["NoArchivedItems"] = "No archived items.",
            ["CategoryNotFound"] = "Category not found.",
            ["LanguageEnglish"] = "English",
            ["LanguageArabic"] = "Arabic",
            ["LinksCount"] = "{0} links",
            ["InvalidUrl"] = "Please enter a valid URL.",
            ["CategoryNameRequired"] = "Category name is required.",
            ["CategoryNameDuplicate"] = "A category with this name already exists.",
            ["SearchCategories"] = "Search categories by name",
            ["NoCategorySearchResults"] = "No categories match your search.",
            ["ShareLinkTitle"] = "Save shared link",
            ["SelectCategory"] = "Select category",
            ["SaveLink"] = "Save link",
            ["ShareNoCategories"] = "Create a category on the home page first.",
            ["LinkSaved"] = "Link saved.",
            ["ShareHint"] = "Choose a category and save the link below.",
            ["ShareCreateCategoryHint"] = "Create a category below to save this link.",
            ["QuickCreateCategory"] = "Quick create category",
            ["SelectCategoryRequired"] = "Please select a category.",
            ["Login"] = "Log in",
            ["Register"] = "Register",
            ["Logout"] = "Log out",
            ["Email"] = "Email",
            ["Password"] = "Password",
            ["ConfirmPassword"] = "Confirm password",
            ["DisplayName"] = "Display name",
            ["RememberMe"] = "Remember me",
            ["InvalidCredentials"] = "Invalid email or password.",
            ["EmailNotConfirmed"] = "Please confirm your email address before signing in.",
            ["EmailConfirmedSuccess"] = "Email confirmed. You can sign in now.",
            ["EmailConfirmationFailed"] = "Email confirmation link is invalid or expired.",
            ["PasswordsDoNotMatch"] = "Passwords do not match.",
            ["LoginFailed"] = "Login failed. Please try again.",
            ["RegisterFailed"] = "Registration failed. Please try again.",
            ["RegistrationSuccessful"] = "Account created. Sign in to continue.",
            ["RegistrationConfirmEmail"] = "Account created. Check your email to confirm your address before signing in.",
            ["Personal"] = "Personal",
            ["Shared"] = "Shared",
            ["FilterAll"] = "All",
            ["FilterMine"] = "Mine",
            ["FilterShared"] = "Shared",
            ["ViewFilter"] = "Show",
            ["SaveTo"] = "Save to",
            ["GroupLabel"] = "{0}",
            ["SharedWithGroup"] = "Shared · {0}",
            ["CreateGroup"] = "Create a group",
            ["GroupName"] = "Group name",
            ["GroupNameRequired"] = "Group name is required.",
            ["NoGroupsYet"] = "Create a group to share categories with others.",
            ["PendingInvites"] = "Pending invites",
            ["InvitePrompt"] = "You were invited to join \"{0}\" by {1}.",
            ["AcceptInvite"] = "Accept",
            ["DeclineInvite"] = "Decline",
            ["YourGroup"] = "Your group",
            ["YourGroups"] = "Your groups",
            ["GroupsNav"] = "Groups",
            ["GroupsPageTitle"] = "Groups",
            ["GroupsPageDescription"] = "Create groups, accept invites, and manage members.",
            ["ManageGroupsLink"] = "Manage groups",
            ["ManageMembers"] = "Manage members",
            ["UserAlreadyInGroup"] = "You are already a member of a group.",
            ["GroupMembersTitle"] = "Members · {0}",
            ["GroupNotFound"] = "Group not found or you are not a member.",
            ["InviteMember"] = "Invite member",
            ["SendInvite"] = "Send invite",
            ["MemberList"] = "Members",
            ["NoMembersYet"] = "No members yet.",
            ["RoleAdmin"] = "Admin",
            ["RoleMember"] = "Member",
            ["RemoveMember"] = "Remove",
            ["LeaveGroup"] = "Leave group",
            ["InviteEmailRequired"] = "Email is required.",
            ["InviteSent"] = "Invite sent.",
            ["InviteFailed"] = "Could not send invite.",
            ["InviteeNotFound"] = "No registered account matches that email.",
            ["InviteeEmailUnconfirmed"] = "That user has not confirmed their email address.",
            ["InviteeInGroup"] = "That user is already in a group.",
            ["InviteeAlreadyMember"] = "That user is already a member of this group.",
            ["GroupFull"] = "This group is full.",
            ["InviteAlreadyPending"] = "An invite is already pending for that user.",
            ["RemoveMemberFailed"] = "Could not remove member.",
            ["LeaveGroupFailed"] = "Could not leave group.",
            ["CannotLeaveAsLastAdmin"] = "You are the only admin. Remove other members before leaving.",
            ["InviteAcceptFailed"] = "Could not accept the invite.",
            ["Settings"] = "Settings",
            ["SettingsDescription"] = "Manage your account and preferences.",
            ["LanguagePreference"] = "Language",
            ["ProfileSettings"] = "Profile",
            ["PasswordSettings"] = "Password",
            ["SaveChanges"] = "Save changes",
            ["ProfileUpdated"] = "Profile updated.",
            ["ProfileUpdateFailed"] = "Could not update profile.",
            ["ChangePassword"] = "Change password",
            ["ChangePasswordHint"] = "We'll email you a link to set a new password.",
            ["DeactivateAccount"] = "Deactivate account",
            ["DeactivateAccountHint"] = "Your links and categories stay in the system, but you will not be able to sign in again.",
            ["DeactivateConfirmationLabel"] = "Type your display name or DEACTIVATE to confirm",
            ["ConfirmDeactivate"] = "Confirm deactivation",
            ["Cancel"] = "Cancel",
            ["DeactivateAccountFailed"] = "Could not deactivate account.",
            ["AccountDeactivated"] = "This account has been deactivated.",
            ["AccountDeactivatedSuccess"] = "Your account has been deactivated.",
            ["ForgotPassword"] = "Forgot password",
            ["ForgotPasswordHint"] = "Enter your email and we'll send you a reset link.",
            ["SendResetLink"] = "Send reset link",
            ["ForgotPasswordSent"] = "If an account exists for that email, a reset link has been sent.",
            ["ForgotPasswordFailed"] = "Could not send reset email. Try again.",
            ["BackToLogin"] = "Back to login",
            ["ResetPassword"] = "Reset password",
            ["ResetPasswordInvalidLink"] = "This reset link is invalid or expired.",
            ["ResetPasswordFailed"] = "Could not reset password. Try again.",
            ["PasswordResetSuccess"] = "Password updated. You can sign in now.",
            ["ResendConfirmation"] = "Resend confirmation email",
            ["ResendConfirmationSent"] = "If an unconfirmed account exists, a new confirmation email has been sent.",
            ["ResendConfirmationFailed"] = "Could not resend confirmation email.",
            ["ResendConfirmationEmailRequired"] = "Enter your email address first.",
        },
        ["ar"] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["AppTitle"] = "إدارة وجبات العائلة",
            ["Home"] = "الرئيسية",
            ["Archive"] = "الأرشيف",
            ["FavoriteCategories"] = "الفئات المفضلة",
            ["AllCategories"] = "كل الفئات",
            ["AddCategory"] = "إضافة فئة",
            ["CategoryName"] = "اسم الفئة",
            ["Create"] = "إنشاء",
            ["Delete"] = "حذف",
            ["Restore"] = "استعادة",
            ["Favorite"] = "تفضيل",
            ["Unfavorite"] = "إلغاء التفضيل",
            ["Open"] = "فتح",
            ["Back"] = "رجوع",
            ["FavoriteLinks"] = "الروابط المفضلة",
            ["AllLinks"] = "كل الروابط",
            ["AddLink"] = "إضافة رابط",
            ["LinkTitleEn"] = "العنوان (إنجليزي، اختياري)",
            ["LinkTitleAr"] = "العنوان (عربي، اختياري)",
            ["SearchLinks"] = "ابحث في الروابط بالعنوان أو الرابط",
            ["NoSearchResults"] = "لا توجد روابط مطابقة لبحثك.",
            ["LinkTitle"] = "العنوان (اختياري)",
            ["LinkUrl"] = "الرابط",
            ["LinkNote"] = "ملاحظة (اختياري)",
            ["LoadingPreview"] = "جاري تحميل المعاينة...",
            ["PreviewUnavailable"] = "المعاينة غير متاحة",
            ["ArchivedItems"] = "العناصر المؤرشفة",
            ["ArchivedCategories"] = "الفئات المؤرشفة",
            ["ArchivedLinks"] = "الروابط المؤرشفة",
            ["ArchiveRetentionNotice"] = "تبقى العناصر في الأرشيف لمدة 7 أيام قبل الحذف النهائي.",
            ["NoCategoriesYet"] = "لا توجد فئات بعد. أنشئ أول فئة وجبات.",
            ["NoLinksYet"] = "لا توجد روابط بعد. أضف أول رابط.",
            ["NoArchivedItems"] = "لا توجد عناصر مؤرشفة.",
            ["CategoryNotFound"] = "الفئة غير موجودة.",
            ["LanguageEnglish"] = "الإنجليزية",
            ["LanguageArabic"] = "العربية",
            ["LinksCount"] = "{0} روابط",
            ["InvalidUrl"] = "يرجى إدخال رابط صالح.",
            ["CategoryNameRequired"] = "اسم الفئة مطلوب.",
            ["CategoryNameDuplicate"] = "يوجد فئة بهذا الاسم بالفعل.",
            ["SearchCategories"] = "ابحث في الفئات بالاسم",
            ["NoCategorySearchResults"] = "لا توجد فئات مطابقة لبحثك.",
            ["ShareLinkTitle"] = "حفظ الرابط المشارك",
            ["SelectCategory"] = "اختر الفئة",
            ["SaveLink"] = "حفظ الرابط",
            ["ShareNoCategories"] = "أنشئ فئة من الصفحة الرئيسية أولاً.",
            ["LinkSaved"] = "تم حفظ الرابط.",
            ["ShareHint"] = "اختر فئة واحفظ الرابط أدناه.",
            ["ShareCreateCategoryHint"] = "أنشئ فئة أدناه لحفظ هذا الرابط.",
            ["QuickCreateCategory"] = "إنشاء فئة سريع",
            ["SelectCategoryRequired"] = "يرجى اختيار فئة.",
            ["Login"] = "تسجيل الدخول",
            ["Register"] = "إنشاء حساب",
            ["Logout"] = "تسجيل الخروج",
            ["Email"] = "البريد الإلكتروني",
            ["Password"] = "كلمة المرور",
            ["ConfirmPassword"] = "تأكيد كلمة المرور",
            ["DisplayName"] = "الاسم المعروض",
            ["RememberMe"] = "تذكرني",
            ["InvalidCredentials"] = "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
            ["EmailNotConfirmed"] = "يرجى تأكيد بريدك الإلكتروني قبل تسجيل الدخول.",
            ["EmailConfirmedSuccess"] = "تم تأكيد البريد الإلكتروني. يمكنك تسجيل الدخول الآن.",
            ["EmailConfirmationFailed"] = "رابط تأكيد البريد الإلكتروني غير صالح أو منتهي الصلاحية.",
            ["PasswordsDoNotMatch"] = "كلمتا المرور غير متطابقتين.",
            ["LoginFailed"] = "فشل تسجيل الدخول. حاول مرة أخرى.",
            ["RegisterFailed"] = "فشل إنشاء الحساب. حاول مرة أخرى.",
            ["RegistrationSuccessful"] = "تم إنشاء الحساب. سجّل الدخول للمتابعة.",
            ["RegistrationConfirmEmail"] = "تم إنشاء الحساب. تحقق من بريدك الإلكتروني لتأكيد العنوان قبل تسجيل الدخول.",
            ["Personal"] = "شخصي",
            ["Shared"] = "مشترك",
            ["FilterAll"] = "الكل",
            ["FilterMine"] = "خاص بي",
            ["FilterShared"] = "مشترك",
            ["ViewFilter"] = "عرض",
            ["SaveTo"] = "حفظ في",
            ["GroupLabel"] = "{0}",
            ["SharedWithGroup"] = "مشترك · {0}",
            ["CreateGroup"] = "إنشاء مجموعة",
            ["GroupName"] = "اسم المجموعة",
            ["GroupNameRequired"] = "اسم المجموعة مطلوب.",
            ["NoGroupsYet"] = "أنشئ مجموعة لمشاركة الفئات مع الآخرين.",
            ["PendingInvites"] = "دعوات معلّقة",
            ["InvitePrompt"] = "تمت دعوتك للانضمام إلى \"{0}\" من قبل {1}.",
            ["AcceptInvite"] = "قبول",
            ["DeclineInvite"] = "رفض",
            ["YourGroup"] = "مجموعتك",
            ["YourGroups"] = "مجموعاتك",
            ["GroupsNav"] = "المجموعات",
            ["GroupsPageTitle"] = "المجموعات",
            ["GroupsPageDescription"] = "أنشئ مجموعات، واقبل الدعوات، وأدر الأعضاء.",
            ["ManageGroupsLink"] = "إدارة المجموعات",
            ["ManageMembers"] = "إدارة الأعضاء",
            ["UserAlreadyInGroup"] = "أنت عضو في مجموعة بالفعل.",
            ["GroupMembersTitle"] = "الأعضاء · {0}",
            ["GroupNotFound"] = "المجموعة غير موجودة أو لست عضواً فيها.",
            ["InviteMember"] = "دعوة عضو",
            ["SendInvite"] = "إرسال الدعوة",
            ["MemberList"] = "الأعضاء",
            ["NoMembersYet"] = "لا يوجد أعضاء بعد.",
            ["RoleAdmin"] = "مسؤول",
            ["RoleMember"] = "عضو",
            ["RemoveMember"] = "إزالة",
            ["LeaveGroup"] = "مغادرة المجموعة",
            ["InviteEmailRequired"] = "البريد الإلكتروني مطلوب.",
            ["InviteSent"] = "تم إرسال الدعوة.",
            ["InviteFailed"] = "تعذّر إرسال الدعوة.",
            ["InviteeNotFound"] = "لا يوجد حساب مسجّل بهذا البريد.",
            ["InviteeEmailUnconfirmed"] = "لم يؤكد ذلك المستخدم بريده الإلكتروني.",
            ["InviteeInGroup"] = "ذلك المستخدم عضو في مجموعة بالفعل.",
            ["InviteeAlreadyMember"] = "ذلك المستخدم عضو في هذه المجموعة بالفعل.",
            ["GroupFull"] = "هذه المجموعة ممتلئة.",
            ["InviteAlreadyPending"] = "توجد دعوة معلّقة بالفعل لذلك المستخدم.",
            ["RemoveMemberFailed"] = "تعذّرت إزالة العضو.",
            ["LeaveGroupFailed"] = "تعذّرت مغادرة المجموعة.",
            ["CannotLeaveAsLastAdmin"] = "أنت المسؤول الوحيد. أزل الأعضاء الآخرين قبل المغادرة.",
            ["InviteAcceptFailed"] = "تعذّر قبول الدعوة.",
            ["Settings"] = "الإعدادات",
            ["SettingsDescription"] = "إدارة حسابك وتفضيلاتك.",
            ["LanguagePreference"] = "اللغة",
            ["ProfileSettings"] = "الملف الشخصي",
            ["PasswordSettings"] = "كلمة المرور",
            ["SaveChanges"] = "حفظ التغييرات",
            ["ProfileUpdated"] = "تم تحديث الملف الشخصي.",
            ["ProfileUpdateFailed"] = "تعذّر تحديث الملف الشخصي.",
            ["ChangePassword"] = "تغيير كلمة المرور",
            ["ChangePasswordHint"] = "سنرسل إليك رابطاً عبر البريد لتعيين كلمة مرور جديدة.",
            ["DeactivateAccount"] = "إلغاء تفعيل الحساب",
            ["DeactivateAccountHint"] = "ستبقى روابطك وفئاتك في النظام، لكن لن تتمكن من تسجيل الدخول مجدداً.",
            ["DeactivateConfirmationLabel"] = "اكتب اسمك المعروض أو DEACTIVATE للتأكيد",
            ["ConfirmDeactivate"] = "تأكيد إلغاء التفعيل",
            ["Cancel"] = "إلغاء",
            ["DeactivateAccountFailed"] = "تعذّر إلغاء تفعيل الحساب.",
            ["AccountDeactivated"] = "تم إلغاء تفعيل هذا الحساب.",
            ["AccountDeactivatedSuccess"] = "تم إلغاء تفعيل حسابك.",
            ["ForgotPassword"] = "نسيت كلمة المرور",
            ["ForgotPasswordHint"] = "أدخل بريدك الإلكتروني وسنرسل لك رابط إعادة التعيين.",
            ["SendResetLink"] = "إرسال رابط إعادة التعيين",
            ["ForgotPasswordSent"] = "إذا وُجد حساب لهذا البريد، فقد أُرسل رابط إعادة التعيين.",
            ["ForgotPasswordFailed"] = "تعذّر إرسال بريد إعادة التعيين. حاول مرة أخرى.",
            ["BackToLogin"] = "العودة لتسجيل الدخول",
            ["ResetPassword"] = "إعادة تعيين كلمة المرور",
            ["ResetPasswordInvalidLink"] = "رابط إعادة التعيين غير صالح أو منتهٍ.",
            ["ResetPasswordFailed"] = "تعذّرت إعادة تعيين كلمة المرور. حاول مرة أخرى.",
            ["PasswordResetSuccess"] = "تم تحديث كلمة المرور. يمكنك تسجيل الدخول الآن.",
            ["ResendConfirmation"] = "إعادة إرسال بريد التأكيد",
            ["ResendConfirmationSent"] = "إذا وُجد حساب غير مؤكد، فقد أُرسل بريد تأكيد جديد.",
            ["ResendConfirmationFailed"] = "تعذّر إعادة إرسال بريد التأكيد.",
            ["ResendConfirmationEmailRequired"] = "أدخل بريدك الإلكتروني أولاً.",
        },
    };

    /// <summary>
    /// Looks up a localized string for the given culture, falling back to English then the key itself.
    /// </summary>
    /// <param name="cultureCode">BCP 47 culture code; Arabic variants map to <c>ar</c>, all others to <c>en</c>.</param>
    /// <param name="key">Resource key defined in the string tables.</param>
    /// <returns>The localized value, English fallback, or <paramref name="key"/> when not found.</returns>
    public static string Get(string cultureCode, string key)
    {
        var culture = NormalizeCulture(cultureCode);
        if (Strings.TryGetValue(culture, out var cultureStrings)
            && cultureStrings.TryGetValue(key, out var value))
        {
            return value;
        }

        if (Strings["en"].TryGetValue(key, out var fallback))
        {
            return fallback;
        }

        return key;
    }

    /// <summary>
    /// Looks up a localized format string and applies culture-aware composite formatting.
    /// </summary>
    /// <param name="cultureCode">BCP 47 culture code used for both lookup and formatting.</param>
    /// <param name="key">Resource key whose value is a composite format string.</param>
    /// <param name="arguments">Values substituted into the format string.</param>
    /// <returns>The formatted localized string.</returns>
    public static string Format(string cultureCode, string key, params object[] arguments)
    {
        var format = Get(cultureCode, key);
        return string.Format(System.Globalization.CultureInfo.GetCultureInfo(NormalizeCulture(cultureCode)), format, arguments);
    }

    private static string NormalizeCulture(string cultureCode) =>
        cultureCode.StartsWith("ar", StringComparison.OrdinalIgnoreCase) ? "ar" : "en";
}
