<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LinkNest.Web.Client\LinkNest.Web.Client.csproj">
      <AdditionalProperties>StaticWebAssetProjectMode=Default</AdditionalProperties>
    </ProjectReference>
    <ProjectReference Include="..\..\LinkNest.Api\LinkNest.Api.csproj">
      <ExcludeAssets>contentfiles</ExcludeAssets>
    </ProjectReference>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.2" />
    <PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\LinkNest.Shared\LinkNest.Shared.csproj" />
  </ItemGroup>

</Project>
